// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBAPI.Data;

namespace WEBAPI.Migrations
{
    [DbContext(typeof(ProductoContexto))]
    [Migration("20200816004818_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WEBAPI.Models.Productos", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodProducto")
                        .IsRequired();

                    b.Property<string>("DesProducto");

                    b.Property<string>("ImgProducto");

                    b.Property<string>("NomProducto");

                    b.Property<decimal>("PreComProducto");

                    b.Property<decimal>("PreVenProducto");

                    b.Property<int>("StkMaxProducto");

                    b.Property<int>("StkMinProducto");

                    b.HasKey("IdProducto");

                    b.ToTable("ProductosItems");
                });
#pragma warning restore 612, 618
        }
    }
}
